### ISSUE TITLE
Need clearer error messages

### ISSUE THREAD

**Issue by AlxCzl** [ashwinvis/myst-reader#25]
Hey :wave: Thank you for the amazing tool!

We're currently using pelican to deploy our blog and, since we weren't using your plugin before, we need to convert the meta-data to the new format.
I've had a hard time understanding where the errors were coming from in my files so I've added a few more characters in your plugin to show the exact error in addition to the current error message.

Before:
```
           ERROR    Could not process content/blabla.md                                                                      log.py:96
                    Malformed content or front-matter metadata.
```

After:
```
           ERROR    Could not process content/blabla.md                                                                      log.py:96
                    Malformed content or front-matter metadata:                                                                                                   
                    <string>:0: (ERROR/3) Document or section may not begin with a transition.
```

I guess that it could use a bit more formatting, but this is just a suggestion :smile: please tell me what you think about adding something like this:
`plugins/myst_reader/myst_reader.py:364`
```python
raise MystReaderContentError(
    f"Malformed content or front-matter metadata:\n{err}"
) from err
```

**Comment by ashwinvis** [comment]
Honestly as per docutils, a transition is a `-------`, which is puzzling because that's not what we are doing with MyST markup where we use the same syntax to demarcate the front-matter. So the current  error message explains it for you "Malformed content or **front-matter metadata**" 

But if you think adding the docutils message helps, then sure, go ahead and submit a PR.

**Comment by ashwinvis** [comment]
Also another thing, set `export DEBUG=1` or use `pelican --debug` while building your Pelican blog. It will show the full traceback.

**Comment by AlxCzl** [comment]
The error in itself was just an example (an empty section header right before footnotes), but I find that having the error message show a little more detail helps quite a bit when looking for a problem.

I can submit a PR but if you think that it isn't necessary, I'll just keep this locally :smile: this was just my 2-cents! Will try `DEBUG=1` next time I have that kind of problem.

**Comment by paugier** [comment]
My 2-cents: I also think better messages for errors would be useful! `DEBUG=1` is nice but it is strange that we need that to have a good error message for an error related to the content of the blog.

**Comment by ashwinvis** [comment]
@AlxCzl I thought about a bit more and I think you are right, we should know which line is causing the problem and the docutils error message hints at this. I would welcome this change.

**Comment by AlxCzl** [comment]
Do I just print the errors like I did in my suggestion or do you suggest something a little more sophisticated?

**Comment by ashwinvis** [comment]
Your suggestion is good enough, I think

**Comment by ashwinvis** [comment]
Merging, thanks.
