### ISSUE TITLE
Upgrade to `myst-parser` v4

### ISSUE THREAD

**Issue by kdeldycke** [ashwinvis/myst-reader#29]
Hey @ashwinvis, any plan for a `1.4.0` release to bump the dependency from `myst-parser = "^2.0.0"` to `myst-parser = "^3.0.0"`? 🤗

**Comment by ashwinvis** [comment]
Can you do a PR? Let's see if the tests go through.

**Comment by ashwinvis** [comment]
And it is up on PyPI... :tada: 

Let me know if it works for you

**Comment by kdeldycke** [comment]
@ashwinvis seems to work on my side. Thanks for the release!
