### ISSUE TITLE
Update for more recent versions myst-parser?

### ISSUE THREAD

**Issue by paugier** [ashwinvis/myst-reader#4]
I tried to use [pelican-myst-reader](https://github.com/ashwinvis/myst-reader) and I get some issues (for example `admonition`s are not displayed correctly). Before going further, I'd like to be able to try with more recent versions of myst-parser but poetry complains about the fact that pelican-myst-reader is only compatible with myst-parser `^0.14.0`.

I guess this limitation might not be related to a real problem with more recent version of myst-parser and that one just needs to check what it gives and to release a new version.

**Comment by ashwinvis** [comment]
I tried to upgrade to the `myst-parser==^0.18.0` and it seems like they have overhauled their API. Will need some work to get it up and running.

**Comment by paugier** [comment]
Please tell me if I can be useful for anything on this one.

**Comment by ashwinvis** [comment]
Most of the functionality have been restored. One test suite remains to be fixed. It will be nice if you can take a look, verify the output and fix it.
