### ISSUE TITLE
Admonitions not correctly rendered - corresponding CSS missing

### ISSUE THREAD

**Issue by paugier** [ashwinvis/myst-reader#5]
I guess I don't understand something quite evident. It seems that some basic css are missing to represent correctly some elements. For example, admonitions are not rendered correctly. 

Which css files should be included?

Is there a Pelican theme compatible with MyST?

**Comment by paugier** [comment]
Same things for math with $. With 

```python
MYST_EXTENSIONS = [
    "amsmath",
    "dollarmath",
]
```

the equation are converted to 

```html
<span class="math notranslate nohighlight">
      \(F_h\)
</span>
```
but it does not render correctly.

**Comment by paugier** [comment]
Oups, for the math equations, the problem was actually that the theme did not include the Mathjax script. So no real issue.

**Comment by ashwinvis** [comment]
I am not aware of any Pelican+MyST heme, but it would suffice to manually unwrap / compile some of the [SASS files in the sphinx-book-theme](https://github.com/executablebooks/sphinx-book-theme/tree/master/src/sphinx_book_theme/assets) into normal CSS and vendor it in your own pelican website sources.

If you manage to find such a solution, we could add it in the README / docs here as an example. PRs welcome.

**Comment by ashwinvis** [comment]
Closing because there is not much to be done
